### ISSUE TITLE
Allow adding tasks by specifying a country/continent from geofabrikbounds 

### ISSUE THREAD

**Issue by masain** [GIScience/OSM-realtime-update#14]
e.g. Africa instead of WKT polygon or GeoJSON

**Comment by TimMcCauley** [comment]
As it doesn't work with bounds as input for these spatial dimensions

**Comment by sedot42** [comment]
The client UI does not support adding tasks with a geofabrik string. Usage:
`curl --data 'name=Togo&coverage=togo&updateInterval=10' http://localhost:1234/api/tasks`
