### ISSUE TITLE
Create pbf files for areas covering multiple geofabrik regions

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/OSM-realtime-update#16]
Currently the input area for realtimeosm tasks can't intersect with multiple major geofabrik regions.

Let's see how we can fix this:
* idea 1: get pbf from overpass api
* idea 2: merge pbf from geofabrik regions.

**Comment by sedot42** [comment]
Idea 1: 
We need to know whether overpass API can handle the load. The Wiki[https://wiki.openstreetmap.org/wiki/Overpass_API#Limitations] specifically states that downloading large regions is advised against. 
I just ran a query on our local overpass API:
```
(
   node(29.48,-51.52,52.09,14.45);
   way(29.48,-51.52,52.09,14.45);
   relation(29.48,-51.52,52.09,14.45);
);
out count;
``` 
The bounding box (format: South, West, North, East) mostly covers the atlantic. It fails saying that it needs at least 513MB RAM. So I guess overpass cannot handle our loads. But feel free to experiment with your own bounding boxes!
