### ISSUE TITLE
Add name of geofabrik region to coverage geojson

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/OSM-realtime-update#17]
When using the geofabrik name to create a task in realtimeosm, the geometry will be generated as geojson.

We should add an attribute `geofabrik_name` to this geojson. This will help us to identify which tasks have been created with geofabrik names.

**Comment by masain** [comment]
the name of the geofabrik extent is already included:
```
"coverage":{
	"type":"Feature",
	"geometry":{"type":"Polygon","coordinates":[[]]},
	"properties":{"name":"north-america"}
	}
```
